# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrfcBORxk2CkQgOMb8RXI49SBjmg4kAi
"""

lista = [1,2,3,4,5,6,7,8,9,10]
num1 = input ("Digite um número: ")
operador = input ("Digite o operador (+, -, *, /):")
num1_convert = int(num1)

for i, val in enumerate(lista): # for onde o "i" é o indice da variável lista, o val recebe cada elemento da lista
  if num1_convert >= 11:
    print("Número maior que 10, favor inserir numeração de 0 á 10!")
    break
  elif operador == '+':
      print(num1_convert ,'+', val, '=', num1_convert + val)
  elif operador == '-':
      print(num1_convert ,'-', val, '=', num1_convert - val)
  elif operador == '*':
      print(num1_convert ,'*', val, '=', num1_convert * val)
  elif operador == '/':
      print(num1_convert ,'/', val, '=', num1_convert / val)